# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import soldier_pb2 as soldier__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63onnector.proto\x1a\rsoldier.proto\"8\n\nCoordinate\x12\x0e\n\x01x\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x0e\n\x01y\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x04\n\x02_xB\x04\n\x02_y\"R\n\rMissileStrike\x12\x1d\n\x03pos\x18\x01 \x01(\x0b\x32\x0b.CoordinateH\x00\x88\x01\x01\x12\x11\n\x04type\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x06\n\x04_posB\x07\n\x05_type\"_\n\x03Hit\x12\x11\n\x04hits\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05kills\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x13\n\x06points\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\x07\n\x05_hitsB\x08\n\x06_killsB\t\n\x07_points\"(\n\x06Points\x12\x13\n\x06points\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\t\n\x07_points\"1\n\tTimestamp\x12\x16\n\ttimestamp\x18\x01 \x01(\x02H\x00\x88\x01\x01\x42\x0c\n\n_timestamp2\xd8\x01\n\tPassAlert\x12#\n\tSendAlert\x12\x0e.MissileStrike\x1a\x04.Hit\"\x00\x12\x35\n\x0cRegisterNode\x12\x14.soldier.SoldierData\x1a\r.soldier.void\"\x00\x12,\n\rRegisterEnemy\x12\n.Timestamp\x1a\r.soldier.void\"\x00\x12 \n\x06\x41ttack\x12\x0e.MissileStrike\x1a\x04.Hit\"\x00\x12\x1f\n\tGetPoints\x12\x07.Points\x1a\x07.Points\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connector_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COORDINATE']._serialized_start=34
  _globals['_COORDINATE']._serialized_end=90
  _globals['_MISSILESTRIKE']._serialized_start=92
  _globals['_MISSILESTRIKE']._serialized_end=174
  _globals['_HIT']._serialized_start=176
  _globals['_HIT']._serialized_end=271
  _globals['_POINTS']._serialized_start=273
  _globals['_POINTS']._serialized_end=313
  _globals['_TIMESTAMP']._serialized_start=315
  _globals['_TIMESTAMP']._serialized_end=364
  _globals['_PASSALERT']._serialized_start=367
  _globals['_PASSALERT']._serialized_end=583
# @@protoc_insertion_point(module_scope)
