# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: soldier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsoldier.proto\"6\n\x08Position\x12\x0e\n\x01x\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x0e\n\x01y\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x04\n\x02_xB\x04\n\x02_y\"N\n\x07RedZone\x12\x1b\n\x03pos\x18\x01 \x01(\x0b\x32\t.PositionH\x00\x88\x01\x01\x12\x13\n\x06radius\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x06\n\x04_posB\t\n\x07_radius\"\xb4\x01\n\x0c\x41ttackStatus\x12\x18\n\x0b\x64\x65\x61th_count\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\thit_count\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x13\n\x06points\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x1e\n\x11\x63urrent_commander\x18\x04 \x01(\x05H\x03\x88\x01\x01\x42\x0e\n\x0c_death_countB\x0c\n\n_hit_countB\t\n\x07_pointsB\x14\n\x12_current_commander\"q\n\rSoldierStatus\x12\x13\n\x06is_hit\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x14\n\x07is_sink\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\x13\n\x06points\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\t\n\x07_is_hitB\n\n\x08_is_sinkB\t\n\x07_points\" \n\tBattalion\x12\x13\n\x0bsoldier_ids\x18\x01 \x03(\x05\"\x06\n\x04void2\x81\x01\n\x05\x41lert\x12%\n\x08SendZone\x12\x08.RedZone\x1a\r.AttackStatus\"\x00\x12*\n\x0cUpdateStatus\x12\x08.RedZone\x1a\x0e.SoldierStatus\"\x00\x12%\n\x0ePromoteSoldier\x12\n.Battalion\x1a\x05.void\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soldier_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_POSITION']._serialized_start=17
  _globals['_POSITION']._serialized_end=71
  _globals['_REDZONE']._serialized_start=73
  _globals['_REDZONE']._serialized_end=151
  _globals['_ATTACKSTATUS']._serialized_start=154
  _globals['_ATTACKSTATUS']._serialized_end=334
  _globals['_SOLDIERSTATUS']._serialized_start=336
  _globals['_SOLDIERSTATUS']._serialized_end=449
  _globals['_BATTALION']._serialized_start=451
  _globals['_BATTALION']._serialized_end=483
  _globals['_VOID']._serialized_start=485
  _globals['_VOID']._serialized_end=491
  _globals['_ALERT']._serialized_start=494
  _globals['_ALERT']._serialized_end=623
# @@protoc_insertion_point(module_scope)
