# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmulti.proto\"\x10\n\x0e\x45ndTurnRequest\"!\n\x0f\x45ndTurnResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2;\n\x0bGameService\x12,\n\x07\x65ndTurn\x12\x0f.EndTurnRequest\x1a\x10.EndTurnResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multi_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ENDTURNREQUEST']._serialized_start=15
  _globals['_ENDTURNREQUEST']._serialized_end=31
  _globals['_ENDTURNRESPONSE']._serialized_start=33
  _globals['_ENDTURNRESPONSE']._serialized_end=66
  _globals['_GAMESERVICE']._serialized_start=68
  _globals['_GAMESERVICE']._serialized_end=127
# @@protoc_insertion_point(module_scope)
