# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timestamp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftimestamp.proto\"\x07\n\x05\x45mpty\"\x1b\n\tTimestamp\x12\x0e\n\x06micros\x18\x01 \x01(\x02\x32)\n\x08\x45xchange\x12\x1d\n\x05order\x12\n.Timestamp\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timestamp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=19
  _globals['_EMPTY']._serialized_end=26
  _globals['_TIMESTAMP']._serialized_start=28
  _globals['_TIMESTAMP']._serialized_end=55
  _globals['_EXCHANGE']._serialized_start=57
  _globals['_EXCHANGE']._serialized_end=98
# @@protoc_insertion_point(module_scope)
